### ISSUE TITLE
Use the sql builder instead of writing manual queries

### ISSUE THREAD

**Issue by dejanzele** [G-Research/unicorn-history-server#154]
We should use the builder defined here https://github.com/G-Research/yunikorn-history-server/blob/main/internal/database/sql/builder.go

Example usage - https://github.com/G-Research/yunikorn-history-server/blob/main/internal/database/repository/application.go#L142-L146

**Comment by richscott** [comment]
I investigated the current state of our db layer logic, and found the following usage:
```
internal/database/repository/application.go
        - GetApplicationByID does raw SELECT with named columns, using single ID parameter
        - GetAllApplications uses builder
        - GetAppsPerParititionPerQueue uses builder

internal/database/repository/queue.go
        - GetAllQueues does raw SELECT with named columns, and no parameters
        - GetQueue does raw SELECT with named columns, using single queueID parameter
        - GetQueuesInPartition does raw SELECT with named columns, using single partitionID parameter

internal/database/repository/partitions.go
        - GetAllPartitions uses builder
        - GetPartitionByID does raw SELECT with named columns, using single partitionID param

internal/database/repository/node.go
        -  GetNodesPerPartition uses builder

internal/database/repository/history.go
        -  GetApplicationsHistory uses builder
        -  GetContainersHistory uses builder
```

I am omitting functions that do non-SELECT db operations, such as UPDATE, DELETE, etc - as the SQL builder code does not support those. We should probably discuss if we want to rework the other ones - the remaining ones all just use a single query parameter. If the pgx driver preserves column-order in its responses for a full `SELECT *`-type query, we can coalesce the numerous column specifications down into a single `SelectAll()`.

**Comment by dave-gantenbein** [comment]
Not going to change course on db access at this time.
