### ISSUE TITLE
Add setup/teardown logic for running multiple integration tests in same test instance

### ISSUE THREAD

**Issue by richscott** [G-Research/unicorn-history-server#82]
As we add more integration tests to YHS, it may cause the overall test run to become quite a bit slower if each test function does its own setup of the Yunikorn server, Postgres db, YHS, etc, and then shutdown/terminate each one when the test func is finished. We should consider creating some helper logic that does a single, one-time setup of the server(s), then have all the integration tests run, then a single tear-down operation. (To ensure a clean state for test funcs, we may not want to do this for all services, or maybe have helper(s) to clear the YHS database between test funcs.)

We can use the Go standard library's `TestMain` func support (see https://pkg.go.dev/testing) to simulate one-time setup/teardown, or we could use the `TestSuite` facility in the `testify` library (we already use `testify/assert`) to set up structured sets of tests and easily declare helper funcs to run before/after both test-sets and individual test funcs - see https://pkg.go.dev/github.com/stretchr/testify/suite .

**Comment by sudiptob2** [comment]
Used `TestMain` in #100. Hopefully, it partially covers this issue.

**Comment by sudiptob2** [comment]
I investigated the issue and found the following information. There are several integration tests in the repository:

1. `TestRESTClient_GetPartitions_Integration`
2. `TestMigrator_Integration`
3. `TestNewComponent_Integration`
4. `TestService_Readiness_Integration`
5. `TestClient_sync_Integration`

At the beginning of all the integration tests, a cluster is set up, and `postgres`, `migrations` are run during the `create_cluster` phase. After this, for some tests, we create a new schema and run the migration again as needed (e.g., see `TestMigrator_Integration` and `TestClient_sync_Integration`). This approach provides a fresh start for those particular tests.

In the cleanup phase, the cluster and all its resources, including the database, are deleted once all the integration tests have been completed.

**Remarks:** For the existing integration tests, the scope for common setup/teardown logic is limited. There is not much common logic. Also, we already have a common logic for creating and deleting the cluster once for all integration tests. In the future, while creating new integration tests, we can consider implementing setup/teardown logic for the sets of integration tests that might need it.
